services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: netbooks
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  pgdata: