services:
  mysql:
    image: mysql:8.0
    container_name: netbooks-mysql-container
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: netbooks
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '3307:3306'

volumes:
  mysqldata: