package app.netbooks.backend.connections;

import java.sql.Array;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

public class DatabaseConnection implements AutoCloseable {
    private Connection connection;

    protected DatabaseConnection(Connection connection) {
        this.connection = connection;
    };
    
    public Statement createStatement() throws SQLException {
        return this.connection.createStatement();
    };

    public PreparedStatement prepareStatement(
        String query
    ) throws SQLException {
        return this.connection.prepareStatement(query);
    };

    public PreparedStatement prepareStatement(
        String query,
        boolean returnAutoGeneratedKeys
    ) throws SQLException {
        if(returnAutoGeneratedKeys) return this.connection.prepareStatement(
            query, 
            Statement.RETURN_GENERATED_KEYS
        );

        return this.prepareStatement(query);
    };

    @Override
    public void close() throws SQLException {
        this.connection.close();
    };
};