import { Book } from "@stores/useBook";
import bannerImg from "@assets/test-banner.jpeg";

const coverImg =
  "https://blog-cdn.reedsy.com/directories/gallery/248/large_65b0ae90317f7596d6f95bfdd6131398.jpg";

export function getMockedBooks(): Book[] {
  return [
    {
      id: 1,
      isbn: 9781234567001,
      title: "Além da Porta do Oceano",
      numPages: 328,
      publishedIn: new Date("2023-04-10"),
      publisher: "Vow Press",
      description:
        "Um romance de fantasia juvenil centrado em telepatia e fuga. A história acompanha Kallista, uma jovem telepata que desperta no isolado Vale sem memória de seu passado. Durante uma década, ela treina como soldado sob a liderança de Valeria Reed, uma guerreira telepata lendária, na enigmática organização militar conhecida como Vow.",
      classification: 8.6,
      tags: [
        "Fantasia",
        "Mistério",
        "Telepatia",
        "Aventura",
        "Fuga",
        "Juvenil",
      ],
      authors: [{ id: 1, name: "Amisha Sathi" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 2,
      isbn: 9781234567002,
      title: "Fragmentos do Éter",
      numPages: 412,
      publishedIn: new Date("2022-09-12"),
      publisher: "Nebula Books",
      description:
        "Uma arqueóloga espacial descobre fragmentos de uma civilização capaz de manipular o tempo.",
      classification: 4.2,
      tags: ["Sci-fi", "Viagem no Tempo"],
      authors: [{ id: 2, name: "Carlos L. Meirelles" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 3,
      isbn: 9781234567003,
      title: "Os Olhos do Guardião",
      numPages: 295,
      publishedIn: new Date("2021-01-20"),
      publisher: "Editora Mística",
      description:
        "Um menino cego herda um poder ancestral que o permite enxergar o destino das pessoas.",
      classification: 4.6,
      tags: ["Fantasia", "Aventura", "Magia"],
      authors: [{ id: 3, name: "Helena Castro" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 4,
      isbn: 9781234567004,
      title: "As Cores da Tempestade",
      numPages: 376,
      publishedIn: new Date("2023-07-08"),
      publisher: "Tempus Livros",
      description:
        "Em um mundo onde emoções controlam o clima, uma jovem com raiva incontrolável ameaça destruir tudo.",
      classification: 4.5,
      tags: ["Fantasia", "Distopia"],
      authors: [{ id: 4, name: "Renata F. Lemos" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 5,
      isbn: 9781234567005,
      title: "O Último Sopro de Avalon",
      numPages: 344,
      publishedIn: new Date("2019-11-15"),
      publisher: "Arthurian House",
      description:
        "O ciclo de Avalon chega ao fim com a última sacerdotisa buscando restaurar o equilíbrio místico.",
      classification: 4.0,
      tags: ["Fantasia", "Mitologia"],
      authors: [{ id: 5, name: "Diana McKnight" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 6,
      isbn: 9781234567006,
      title: "Eco de Silêncio",
      numPages: 301,
      publishedIn: new Date("2020-06-01"),
      publisher: "Editora Voz Interior",
      description:
        "Em um mundo onde ninguém pode falar, a protagonista descobre que sua voz pode libertar ou destruir.",
      classification: 4.3,
      tags: ["Distopia", "Drama"],
      authors: [{ id: 6, name: "Miguel Serafim" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 7,
      isbn: 9781234567007,
      title: "Cidade Submersa",
      numPages: 389,
      publishedIn: new Date("2021-12-02"),
      publisher: "Ocean Press",
      description:
        "Após um desastre ambiental, uma cidade é construída sob o mar, cheia de segredos esquecidos.",
      classification: 4.7,
      tags: ["Sci-fi", "Mistério", "Ambiental"],
      authors: [{ id: 7, name: "Laura Nishida" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 8,
      isbn: 9781234567008,
      title: "Sombras em Duralith",
      numPages: 472,
      publishedIn: new Date("2022-02-22"),
      publisher: "Orbe Fantástico",
      description:
        "Uma guerra esquecida retorna quando artefatos sombrios ressurgem do subsolo de Duralith.",
      classification: 4.1,
      tags: ["Fantasia", "Guerra", "Magia Negra"],
      authors: [{ id: 8, name: "João R. Farias" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 9,
      isbn: 9781234567009,
      title: "Código Invertido",
      numPages: 265,
      publishedIn: new Date("2018-08-19"),
      publisher: "Bitpress",
      description:
        "Um hacker descobre um código que pode mudar a realidade digital — e o mundo físico.",
      classification: 3.9,
      tags: ["Techno-thriller", "Hackers", "IA"],
      authors: [{ id: 9, name: "Fernanda Lopes" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 10,
      isbn: 9781234567010,
      title: "Chamas de Um Passado",
      numPages: 311,
      publishedIn: new Date("2020-03-30"),
      publisher: "Memória Editorial",
      description:
        "Uma historiadora descobre um diário que reconta sua vida sob uma nova luz — e com perigos reais.",
      classification: 4.4,
      tags: ["Drama", "Mistério", "Histórico"],
      authors: [{ id: 10, name: "Ana Beatriz Ramos" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 100,
      isbn: 9781234567001,
      title: "Além da Porta do Oceano",
      numPages: 328,
      publishedIn: new Date("2023-04-10"),
      publisher: "Vow Press",
      description:
        "Kallista acorda sem memória em um vale isolado. Treinada como telepata, ela busca fugir da organização que a controla.",
      classification: 4.8,
      tags: ["Fantasia", "Mistério", "Telepatia"],
      authors: [{ id: 1, name: "Amisha Sathi" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 20,
      isbn: 9781234567002,
      title: "Fragmentos do Éter",
      numPages: 412,
      publishedIn: new Date("2022-09-12"),
      publisher: "Nebula Books",
      description:
        "Uma arqueóloga espacial descobre fragmentos de uma civilização capaz de manipular o tempo.",
      classification: 4.2,
      tags: ["Sci-fi", "Viagem no Tempo"],
      authors: [{ id: 2, name: "Carlos L. Meirelles" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 30,
      isbn: 9781234567003,
      title: "Os Olhos do Guardião",
      numPages: 295,
      publishedIn: new Date("2021-01-20"),
      publisher: "Editora Mística",
      description:
        "Um menino cego herda um poder ancestral que o permite enxergar o destino das pessoas.",
      classification: 4.6,
      tags: ["Fantasia", "Aventura", "Magia"],
      authors: [{ id: 3, name: "Helena Castro" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 40,
      isbn: 9781234567004,
      title: "As Cores da Tempestade",
      numPages: 376,
      publishedIn: new Date("2023-07-08"),
      publisher: "Tempus Livros",
      description:
        "Em um mundo onde emoções controlam o clima, uma jovem com raiva incontrolável ameaça destruir tudo.",
      classification: 4.5,
      tags: ["Fantasia", "Distopia"],
      authors: [{ id: 4, name: "Renata F. Lemos" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 50,
      isbn: 9781234567005,
      title: "O Último Sopro de Avalon",
      numPages: 344,
      publishedIn: new Date("2019-11-15"),
      publisher: "Arthurian House",
      description:
        "O ciclo de Avalon chega ao fim com a última sacerdotisa buscando restaurar o equilíbrio místico.",
      classification: 4.0,
      tags: ["Fantasia", "Mitologia"],
      authors: [{ id: 5, name: "Diana McKnight" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 60,
      isbn: 9781234567006,
      title: "Eco de Silêncio",
      numPages: 301,
      publishedIn: new Date("2020-06-01"),
      publisher: "Editora Voz Interior",
      description:
        "Em um mundo onde ninguém pode falar, a protagonista descobre que sua voz pode libertar ou destruir.",
      classification: 4.3,
      tags: ["Distopia", "Drama"],
      authors: [{ id: 6, name: "Miguel Serafim" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 70,
      isbn: 9781234567007,
      title: "Cidade Submersa",
      numPages: 389,
      publishedIn: new Date("2021-12-02"),
      publisher: "Ocean Press",
      description:
        "Após um desastre ambiental, uma cidade é construída sob o mar, cheia de segredos esquecidos.",
      classification: 4.7,
      tags: ["Sci-fi", "Mistério", "Ambiental"],
      authors: [{ id: 7, name: "Laura Nishida" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 80,
      isbn: 9781234567008,
      title: "Sombras em Duralith",
      numPages: 472,
      publishedIn: new Date("2022-02-22"),
      publisher: "Orbe Fantástico",
      description:
        "Uma guerra esquecida retorna quando artefatos sombrios ressurgem do subsolo de Duralith.",
      classification: 4.1,
      tags: ["Fantasia", "Guerra", "Magia Negra"],
      authors: [{ id: 8, name: "João R. Farias" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 90,
      isbn: 9781234567009,
      title: "Código Invertido",
      numPages: 265,
      publishedIn: new Date("2018-08-19"),
      publisher: "Bitpress",
      description:
        "Um hacker descobre um código que pode mudar a realidade digital — e o mundo físico.",
      classification: 3.9,
      tags: ["Techno-thriller", "Hackers", "IA"],
      authors: [{ id: 9, name: "Fernanda Lopes" }],
      cover: coverImg,
      banner: bannerImg,
    },
    {
      id: 101,
      isbn: 9781234567010,
      title: "Chamas de Um Passado",
      numPages: 311,
      publishedIn: new Date("2020-03-30"),
      publisher: "Memória Editorial",
      description:
        "Uma historiadora descobre um diário que reconta sua vida sob uma nova luz — e com perigos reais.",
      classification: 4.4,
      tags: ["Drama", "Mistério", "Histórico"],
      authors: [{ id: 10, name: "Ana Beatriz Ramos" }],
      cover: coverImg,
      banner: bannerImg,
    },
  ];
}
